const images = {
  a: require('../assets/Alfabeto/a.png'),
  b: require('../assets/Alfabeto/b.png'),
  c: require('../assets/Alfabeto/c.png'),
  d: require('../assets/Alfabeto/d.png'),
  e: require('../assets/Alfabeto/e.png'),
  f: require('../assets/Alfabeto/f.png'),
  g: require('../assets/Alfabeto/g.png'),
  h: require('../assets/Alfabeto/h.png'),
  i: require('../assets/Alfabeto/i.png'),
  j: require('../assets/Alfabeto/j.png'),
  k: require('../assets/Alfabeto/k.png'),
  l: require('../assets/Alfabeto/l.png'),
  m: require('../assets/Alfabeto/m.png'),
  n: require('../assets/Alfabeto/n.png'),
  o: require('../assets/Alfabeto/o.png'),
  p: require('../assets/Alfabeto/p.png'),
  q: require('../assets/Alfabeto/q.png'),
  r: require('../assets/Alfabeto/r.png'),
  s: require('../assets/Alfabeto/s.png'),
  t: require('../assets/Alfabeto/t.png'),
  u: require('../assets/Alfabeto/u.png'),
  v: require('../assets/Alfabeto/v.png'),
  w: require('../assets/Alfabeto/w.png'),
  x: require('../assets/Alfabeto/x.png'),
  y: require('../assets/Alfabeto/y.png'),
  z: require('../assets/Alfabeto/z.png'),
};

export default images;
